version: '3.8'

services:
  app:
    container_name: javadev
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    environment: 
      # MongoDB connection details
      MONGODB_URI: mongodb://${ENV_DB_USER}:${ENV_DB_PASSWORD}@db:27017/${ENV_DB_DATABASE}?authSource=admin
      MONGODB_HOST: db
      MONGODB_DATABASE: ${ENV_DB_DATABASE}
      MONGODB_USER: ${ENV_DB_USER}
      MONGODB_PASSWORD: ${ENV_DB_PASSWORD}

      # New Relic configuration
      NEW_RELIC_APP_NAME: psundaramAzureApp
      NEW_RELIC_LICENSE_KEY: 794006b817ba7b42f7b4039d1d20058cFFFFNRAL

    volumes:
      - ../..:/workspaces:cached
      - ./newrelic:/newrelic:ro

    # Modify the command to include the New Relic agent
    command: java -javaagent:/newrelic/newrelic.jar -jar your-application.jar

    network_mode: service:db

  db:
    container_name: mongoserver
    image: mongo
    restart: unless-stopped
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${ENV_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ENV_DB_PASSWORD}

  redis:
    image: redis
    restart: unless-stopped